package com.inti.model;
// Generated 27 oct. 2022, 12:33:32 by Hibernate Tools 5.6.12.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Departement generated by hbm2java
 */
public class Departement implements java.io.Serializable {

	private BigInteger id;
	private String nom;
	private BigInteger numero;
	private Set employes = new HashSet(0);

	public Departement() {
	}

	public Departement(BigInteger id) {
		this.id = id;
	}

	public Departement(BigInteger id, String nom, BigInteger numero, Set employes) {
		this.id = id;
		this.nom = nom;
		this.numero = numero;
		this.employes = employes;
	}

	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public BigInteger getNumero() {
		return this.numero;
	}

	public void setNumero(BigInteger numero) {
		this.numero = numero;
	}

	public Set getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set employes) {
		this.employes = employes;
	}

}
