package com.inti.model;
// Generated 27 oct. 2022, 12:33:32 by Hibernate Tools 5.6.12.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * Employe generated by hbm2java
 */
public class Employe implements java.io.Serializable {

	private BigInteger id;
	private Departement departement;
	private String nom;
	private BigInteger num;
	private Date dateEmbauche;
	private String metier;
	private Double salaire;

	public Employe() {
	}

	public Employe(BigInteger id) {
		this.id = id;
	}

	public Employe(BigInteger id, Departement departement, String nom, BigInteger num, Date dateEmbauche, String metier,
			Double salaire) {
		this.id = id;
		this.departement = departement;
		this.nom = nom;
		this.num = num;
		this.dateEmbauche = dateEmbauche;
		this.metier = metier;
		this.salaire = salaire;
	}

	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public BigInteger getNum() {
		return this.num;
	}

	public void setNum(BigInteger num) {
		this.num = num;
	}

	public Date getDateEmbauche() {
		return this.dateEmbauche;
	}

	public void setDateEmbauche(Date dateEmbauche) {
		this.dateEmbauche = dateEmbauche;
	}

	public String getMetier() {
		return this.metier;
	}

	public void setMetier(String metier) {
		this.metier = metier;
	}

	public Double getSalaire() {
		return this.salaire;
	}

	public void setSalaire(Double salaire) {
		this.salaire = salaire;
	}

}
